# ─── Communication & Collaboration ─────────────────
collaboration:
  label: 'Collaboration'
  permalink: '/tags/collaboration'
  description: 'Topics around teamwork, shared workspaces, and agent collaboration.'
  
communication:
  label: 'Communication'
  permalink: '/tags/communication'
  description: 'Articles focused on messaging, chat, and human-agent interaction.'

# ─── Content, Writing & SEO ────────────────────────
seo:
  label: 'SEO'
  permalink: '/tags/seo'
  description: 'Search Engine Optimization content and tools for organic visibility.'

writing:
  label: 'Writing'
  permalink: '/tags/writing'
  description: 'Agent tasks that involve text generation, summarization, and formatting.'

# ─── Data, Input & Output ──────────────────────────
analytics:
  label: 'Analytics'
  permalink: '/tags/analytics'
  description: 'Data interpretation, dashboards, and performance tracking tools.'

data:
  label: 'Data'
  permalink: '/tags/data'
  description: 'Broad tag for anything involving structured, unstructured, or flowing data.'

insights:
  label: 'Insights'
  permalink: '/tags/insights'
  description: 'High-level takeaways derived from data or agent output.'

input:
  label: 'Input'
  permalink: '/tags/input'
  description: 'Topics related to data input, fields, and user entry.'

knowledge:
  label: 'Knowledge'
  permalink: '/tags/knowledge'
  description: 'Topics related to knowledge bases, embeddings, and internal search.'

output:
  label: 'Output'
  permalink: '/tags/output'
  description: 'What agents generate: text, actions, messages, or media.'

# ─── Backend, Infra & Automation ───────────────────
automation:
  label: 'Automation'
  permalink: '/tags/automation'
  description: 'Agent workflows and systems that automate tasks and processes.'

backend:
  label: 'Backend'
  permalink: '/tags/backend'
  description: 'Workflow logic, infrastructure, APIs, and server-side topics.'

database:
  label: 'Database'
  permalink: '/tags/database'
  description: 'Content covering structured data, queries, and database integrations.'

postgres:
  label: 'Postgres'
  permalink: '/tags/postgres'
  description: 'Content focused on PostgreSQL integrations and queries.'

serverless:
  label: 'Serverless'
  permalink: '/tags/serverless'
  description: 'Topics on deploying agents without managing servers or containers.'
